apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: certificatsurvey
type: Opaque
data:
  # Value: admin123456789012345678901234567890 (32+ chars)
  JWT_SECRET: YWRtaW4xMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
  # Value: certificatsurvey
  POSTGRES_DB: Y2VydGlmaWNhdHN1cnZleQ==
  # Value: cnan_user
  POSTGRES_USER: Y25hbl91c2Vy
  # Value: cnan_secure_pass
  POSTGRES_PASSWORD: Y25hbl9zZWN1cmVfcGFzcw==
  # Serveur SMTP (ex: mail.verital.ae -> bWFpbC52ZXJpdGFsLmFl)
  SMTP_HOST: bWFpbC52ZXJpdGFsLmFl
  # Port SMTP (ex: 465 -> NDY1  ou  587 -> NTg3)
  SMTP_PORT: NDY1
  # Adresse d'expéditeur (ex: "VMCertifs - Verital Marine" <alerts@verital.ae>)
  SMTP_FROM: IlZNQ2VydGlmcyAtIFZlcml0YWwgTWFyaW5lIiA8YWxlcnRzQHZlcml0YWwuYWU+
  # Nom d'utilisateur SMTP (ex: alerts@verital.ae encodé en base64)
  SMTP_USER: YWxlcnRzQHZlcml0YWwuYWU=
  # Mot de passe SMTP (encodé en base64)
  SMTP_PASS: Vk1jczJAMjY=
